title: I'm here to fuck shit up
theme: minima
author: uabbswag
email: privatecowboi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I hope ya'll are ready because I'm gonna document my github journey on here every step of the way. I'm really looking forward to all the things im going to learn, the people I'm going to meet and work with and most of all I know I'm going to have fun every step of the way :)

# social links
twitter_username: n-a # DO NOT include the @ character, or else the build will fail!
github_username:  uabbswag # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
